# Generated by Django 5.0.1 on 2024-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j', '0002_writemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
